#pragma config(Motor,  port2,           FR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           s1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           s2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           s3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           s4,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

/*

=========================================================================================================
___________________________________________________________________________________________________
|  __        __   ________   __     __       __        ______   __     __   _________    ________   |
|  \ \      / /  |   _____|  \ \   / /      /  \      |  _   \  \ \   / /  |___   ___|  |   _____|  |
|   \ \    / /   |  |_____    \ \_/ /      / /\ \     | |_|  /   \ \_/ /       | |      |  |_____   |
|    \ \  / /    |   _____|    ) _ (      / /__\ \    |  _  |     \   /        | |      |   _____|  |
|     \ \/ /     |  |_____    / / \ \    / ______ \   | |_|  \     | |         | |      |  |_____   |
|      \__/      |________|  /_/   \_\  /_/      \_\  |______/     |_|         |_|      |________|  |
|___________________________________________________________________________________________________|

=========================================================================================================
(by Bretton)
*/

// motors listed in clockwise direction
// open side of the robot is front

void drive() {

    int x = vexRT[Ch1];
    int y = vexRT[Ch2];
    int r = vexRT[Ch4];

    motor[FL] = - y - x - r;
    motor[FR] = + y - x - r;
    motor[BR] = + y + x - r;
    motor[BL] = - y + x - r;

}

void shooter() {
    if (vexRT[Btn5D]) {
        motor[s1] = 60;
        motor[s2] = 60;
        motor[s3] = 60;
        motor[s4] = 60;
        } else {
        motor[s1] = 0;
        motor[s2] = 0;
        motor[s3] = 0;
        motor[s4] = 0;
    }
}

void pre_auton() {
    bStopTasksBetweenModes = true;
}

task autonomous() {
    AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
    while (true) {
        drive();
        shooter();
        sleep(20);
    }
}
