#pragma config(Sensor, in1,    Direct,         sensorPotentiometer)
#pragma config(Motor,  port2,           FR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           s1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           s2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           s3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           s4,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

/*

=========================================================================================================
   ___________________________________________________________________________________________________
  |  __        __   ________   __     __       __        ______   __     __   _________    ________   |
  |  \ \      / /  |   _____|  \ \   / /      /  \      |  _   \  \ \   / /  |___   ___|  |   _____|  |
  |   \ \    / /   |  |_____    \ \_/ /      / /\ \     | |_|  /   \ \_/ /       | |      |  |_____   |
  |    \ \  / /    |   _____|    ) _ (      / /__\ \    |  _  |     \   /        | |      |   _____|  |
  |     \ \/ /     |  |_____    / / \ \    / ______ \   | |_|  \     | |         | |      |  |_____   |
  |      \__/      |________|  /_/   \_\  /_/      \_\  |______/     |_|         |_|      |________|  |
  |___________________________________________________________________________________________________|

=========================================================================================================
                                                                                           (by Bretton)
*/

// motors listed in clockwise direction
// open side of the robot is front

void drive() {

    int x = vexRT[Ch4], y = vexRT[Ch3], r = vexRT[Ch1] / 2;

    motor[FL] = - y - x - r;
    motor[FR] = - y + x + r;
    motor[BR] = - y - x + r;
    motor[BL] = + y - x + r;

}

void shooter() {

    motor[s1] = motor[s2] = motor[s3] = motor[s4] = vexRT[Btn5D] * 60;

}

void dd() {
    int lowerLimit = 500;
    int upperLimit = 2400;

    if(SensorValue(Direct)<upperLimit && vexRT[Btn5U])
        motor[s1] = motor[s2] = motor[s3] = motor[s4] = 60;
    else if (SensorValue(Direct)>lowerLimit && vexRT[Btn5D])
        motor[s1] = motor[s2] = motor[s3] = motor[s4] = -60;
    else
        motor[s1] = motor[s2] = motor[s3] = motor[s4] = 0;
}

void pre_auton() {

    bStopTasksBetweenModes = true;

}

task autonomous() {

    AutonomousCodePlaceholderForTesting();

}

task usercontrol() {

    while (true) {
        dd();
        drive();
        //shooter();
        sleep(20);
    }

}
