#pragma config(Motor,  port2,           FR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// motors listed in clockwise direction
// open side of the robot is front

task main() {

	int x, y, r;

	while (true) {

		x = vexRT[Ch1];
		y = vexRT[Ch2];
		r = vexRT[Ch4];

		motor[FL] = - y - x - r;
		motor[FR] = + y - x - r;
		motor[BR] = + y + x - r;
		motor[BL] = - y + x - r;

		sleep(20);

	}

}
