#pragma config(Sensor, in1,    Direct,         sensorPotentiometer)
#pragma config(Motor,  port2,           FR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           s1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           s2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           s3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           s4,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

// motors listed in clockwise direction
// open side of the robot is front

/*

=========================================================================================================
   ___________________________________________________________________________________________________
  |  __        __   ________   __     __       __        ______   __     __   _________    ________   |
  |  \ \      / /  |   _____|  \ \   / /      /  \      |  _   \  \ \   / /  |___   ___|  |   _____|  |
  |   \ \    / /   |  |_____    \ \_/ /      / /\ \     | |_|  /   \ \_/ /       | |      |  |_____   |
  |    \ \  / /    |   _____|    ) _ (      / /__\ \    |  _  |     \   /        | |      |   _____|  |
  |     \ \/ /     |  |_____    / / \ \    / ______ \   | |_|  \     | |         | |      |  |_____   |
  |      \__/      |________|  /_/   \_\  /_/      \_\  |______/     |_|         |_|      |________|  |
  |___________________________________________________________________________________________________|

=========================================================================================================
                                                                                           (by Bretton)
*/

#include "common.c"

#include "autonomous/autonomous.c"

#include "driver_control/base.c"
#include "driver_control/direct_drive.c"
// #include "driver_control/slip_gear.c"

task autonomous() {

    run_autonomous();

}

task usercontrol() {

    while (true) {
        // drive(); controller is broken right now
        shooter();
    }

}
