#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    ShooterPot,     sensorPotentiometer)
#pragma config(Sensor, in3,    PowerExpanderBattery, sensorAnalog)
#pragma config(Sensor, in4,    DumpPotL,       sensorPotentiometer)
#pragma config(Sensor, in5,    DumpPotR,       sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           DUR,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BFR,           tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port3,           BBR,           tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port4,           BBL,           tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           BFL,           tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DLR,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           DLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          DUL,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GYRO_PORT in2

// motors listed in clockwise direction
// dump is front

/*

=========================================================================================================
   ___________________________________________________________________________________________________
  |  __        __   ________   __     __       __        ______   __     __   _________    ________   |
  |  \ \      / /  |   _____|  \ \   / /      /  \      |  _   \  \ \   / /  |___   ___|  |   _____|  |
  |   \ \    / /   |  |_____    \ \_/ /      / /\ \     | |_|  /   \ \_/ /       | |      |  |_____   |
  |    \ \  / /    |   _____|    ) _ (      / /__\ \    |  _  |     \   /        | |      |   _____|  |
  |     \ \/ /     |  |_____    / / \ \    / ______ \   | |_|  \     | |         | |      |  |_____   |
  |      \__/      |________|  /_/   \_\  /_/      \_\  |______/     |_|         |_|      |________|  |
  |___________________________________________________________________________________________________|

=========================================================================================================
                                                                                           (by Bretton)
*/

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"
#include "common.c"
#include "base.c"
#include "dump.c"
#include "lift.c"
#include "lcd.c"
#include "autonomous/autonomous.c"
#include "driver_control/driver_control.c"
